### ISSUE TITLE
Bot stuck on claiming Lunacy from weekly bonus

### ISSUE THREAD

**Issue by i-Ac1D-i** [Samsterr/SirSquirrelAssistant#48]
As the title states, the bot gets stuck when the screen with 250 lunacy and a confirm button appears after claiming the md reward with a weekly bonus. Other than that the bot works so well great job

**Comment by selberia** [comment]
> As the title states, the bot gets stuck when the screen with 250 lunacy and a confirm button appears after claiming the md reward with a weekly bonus. Other than that the bot works so well great job

hello i see you commented this that meansyou understand how to open this macro can you explain to me please?

**Comment by Samsterr** [comment]
@selberia please read the readme on the main page.

**Comment by Samsterr** [comment]
@i-Ac1D-i ill add it in the next update

**Comment by selberia** [comment]
@Samsterr ive read it but i dont have the exe sirsquirrel and im stuck at this part
![image](https://github.com/user-attachments/assets/528358ab-847f-4289-872b-9271412e1b7e)

**Comment by Samsterr** [comment]
Do you happen to just have a file called sirsquirrel. Windows by default hides the extension

**Comment by selberia** [comment]
i have sirsquirel.py

**Comment by Samsterr** [comment]
@selberia https://github.com/Samsterr/SirSquirrelAssistant/releases grab it from here. download the 1.0.3 Update one and then the latest hotfix 3. replace the exe in the update with the hotfix one

**Comment by selberia** [comment]
![image](https://github.com/user-attachments/assets/6971042c-971d-4836-a4f5-81024254628d)
uhhh what may be the reason for this?

**Comment by Samsterr** [comment]
What windows version are you running

**Comment by Samsterr** [comment]
@eugenefedoto ok noted about this. Ill see whats causing the detection
