### ISSUE TITLE
stuck at Lithograph event

### ISSUE THREAD

**Issue by marqoPie** [Samsterr/SirSquirrelAssistant#50]
Cursor hover over SKIP, doesn't progress. 1920x1080. Latest hotfix installed.
[squirrel.log](https://github.com/user-attachments/files/18231378/squirrel.log)
![Lithograph](https://github.com/user-attachments/assets/3ebe5152-2174-4ac4-9fb8-3983c0e4713d)

**Comment by Samsterr** [comment]
@marqoPie you need to give me the offending segment in the log. i dont think you can expect me to tell whats wrong from 5 days of logs. It looks like it clicked the wrong option in litograph but i wouldnt know if the event had changed to have a different subtext involved until i encounter it or have a picture of the options

**Comment by marqoPie** [comment]
I stopped the bot when it happened so I assumed the latest lines would have it. The bot clicks "Scrape out the letters" instead of the upper option "Read the tablet" and then get stuck on skip. I assume it expects to run an advantage check but it doesn't show up since the picked option isn't the one which results in a check. I'll submit a new log in case this happens again.

**Comment by Samsterr** [comment]
@marqoPie ok noted. next time just submit the last few lines of log as part of the post.
